var AppIDs = {
	TF2: 440,
	CSGO: 730,
	Steam: 753
};

var Quality = {
	Normal: 0,
	Genuine: 1,
	UNUSED_RARITY2: 2,
	Vintage: 3,
	UNUSED_RARITY3: 4,
	Unusual: 5,
	Unique: 6,
	Community: 7,
	Valve: 8,
	SelfMade: 9,
	UNUSED_CUSTOMIZED: 10,
	Strange: 11,
	Haunted: 13,
	UNUSED_COMPLETED: 12,
	Collectors: 14
};

//Unlike Quality, Unusual effects have little logic in order of numbery-thingies. Be careful with using index to look up stuff.
var UnusualEffects = {
	"Particle 1": 1,
	"Flying Bits": 2,
	"Nemesis Burst": 3,
	"Community Sparkle": 4,
	"Holy Glow": 5,
	"Green Confetti": 6,
	"Purple Confetti": 7,
	"Haunted Ghosts": 8,
	"Green Energy": 9,
	"Purple Energy": 10,
	"Circling TF Logo": 11,
	"Massed Flies": 12,
	"Burning Flames": 13,
	"Scorching Flames": 14,
	"Searing Plasma": 15,
	"Vivid Plasma": 16,
	"Sunbeams": 17,
	"Circling Peace Sign": 18,
	"Circling Heart": 19,
	"Map Stamps": 20,
	"Genteel Smoke": 28,
	"Stormy Storm": 29,
	"Blizzardy Storm": 30,
	"Nuts n' Bolts": 31,
	"Orbiting Planets": 32,
	"Orbiting Fire": 33,
	"Bubbling": 34,
	"Smoking": 35,
	"Steaming": 36,
	"Flaming Lantern": 37,
	"Cloudy Moon": 38,
	"Cauldron Bubbles": 39,
	"Eerie Orbiting Fire": 40,
	"Knifestorm": 43,
	"Misty Skull": 44,
	"Harvest Moon": 45,
	"It's A Secret To Everybody": 46,
	"Stormy 13th Hour": 47,
	"Attrib_Particle55": 55,
	"Kill-a-Watt": 56,
	"Terror-Watt": 57,
	"Cloud 9": 58,
	"Aces High": 59,
	"Dead Presidents": 60,
	"Miami Nights": 61,
	"Disco Beat Down": 62,
	"Phosphorous": 63,
	"Sulphurous": 64,
	"Memory Leak": 65,
	"Overclocked": 66,
	"Electrostatic": 67,
	"Power Surge": 68,
	"Anti-Freeze": 69,
	"Time Warp": 70,
	"Green Black Hole": 71,
	"Roboactive": 72,
	"Arcana": 73,
	"Spellbound": 74,
	"Chiroptera Venenata": 75,
	"Poisoned Shadows": 76,
	"Something Burning This Way Comes": 77,
	"Hellfire": 78,
	"Darkblaze": 79,
	"Demonflame": 80,
	"Bonzo The All-Gnawing": 81,
	"Amaranthine": 82,
	"Stare From Beyond": 83,
	"The Ooze": 84,
	"Ghastly Ghosts Jr": 85,
	"Haunted Phantasm Jr": 86,
	"Frostbite": 87,
	"Molten Mallard": 88,
	"Morning Glory": 89,
	"Death at Dusk": 90,
	"Abduction": 91,
	"Atomic": 92,
	"Subatomic": 93,
	"Electric Hat Protector": 94,
	"Magnetic Hat Protector": 95,
	"Voltaic Hat Protector": 96,
	"Galactic Codex": 97,
	"Ancient Codex": 98,
	"Nebula": 99,
	"Death by Disco": 100,
	"It's a mystery to everyone": 101,
	"It's a puzzle to me ": 102,
	"Ether Trail": 103,
	"Nether Trail": 104,
	"Ancient Eldritch": 105,
	"Eldritch Flame": 106,
	"Hot": 701,
	"Isotope": 702,
	"Cool": 702,
	"Energy Orb": 704,
	"Showstopper": 3001,
	//"Showstopper": 3002, //yes it shows up twice no its not a typo
	"Holy Grail": 3003,
	"'72": 3004, //again, not a typo, '72 is the effect
	"Fountain of Delight": 3005,
	"Screaming Tiger": 3006,
	"Skill Gotten Gains": 3007,
	"Midnight Whirlwind": 3008,
	"Silver Cyclone": 3009,
	"Mega Strike": 3010,
	"Haunted Phantasm": 3011,
	"Ghastly Ghosts": 3012
};

module.exports = {
	Quality: Quality,
	UnusualEffects: UnusualEffects,
	AppIDs: AppIDs
}